export const defaultProps = {
    __TYPE: 'ColorPicker',
    value: null,
    defaultColor: 'ff0000',
    inline: false,
    format: 'hex',
    disabled: false,
    tabIndex: null,
    autoZIndex: true,
    baseZIndex: 0,
    appendTo: 'body',
    autoFocus: false,
    inputId: null,
    inputStyle: null,
    inputClassName: null,
    overlayStyle: null,
    overlayClassName: null,
    tooltip: null,
    tooltipOptions: null,
    transitionOptions: null,
    onChange: null,
    onHide: null,
    onShow: null
};
