export const defaultProps = {
    __TYPE: 'ToggleSwitch',
    checked: false,
    trueValue: true,
    falseValue: false,
    disabled: false,
    invalid: false,
    inputId: null,
    inputRef: null,
    inputStyle: null,
    inputClassName: null,
    name: null,
    onBlur: null,
    onChange: null,
    onFocus: null,
    tabIndex: null,
    tooltip: null,
    tooltipOptions: null,
    ariaLabel: null,
    ariaLabelledby: null
};
