export const defaultProps = {
    __TYPE: 'Button',
    style: null,
    className: null,
    disabled: false,
    label: null,
    icon: null,
    iconPos: 'left',
    iconClassName: null,
    badge: null,
    badgeClassName: null,
    badgeSeverity: 'secondary',
    loading: false,
    loadingIcon: null,
    link: false,
    severity: null,
    raised: false,
    rounded: false,
    text: false,
    outlined: false,
    size: null,
    plain: false,
    fluid: null,
    tooltip: null,
    tooltipOptions: null,
    children: undefined
};
