export const defaultProps = {
    __TYPE: 'RadioButton',
    id: null,
    style: null,
    className: null,
    value: null,
    checked: false,
    binary: true, // @todo: ask about this
    name: null,
    variant: null,
    invalid: false,
    required: false,
    disabled: false,
    readOnly: false,
    tabIndex: null,
    inputId: null,
    inputStyle: null,
    inputClassName: null,
    ariaLabel: null,
    ariaLabelledBy: null,
    autoFocus: false,
    onChange: null,
    onClick: null,
    tooltip: null,
    tooltipOptions: null,
    children: undefined
};
